name: CI for v1 Module

on:
  push:
    paths-ignore:
      - README.md
      - .github/workflows/test-v2.yml
      - 'v2/**'
  pull_request:
    paths-ignore:
      - README.md
      - .github/workflows/test-v2.yml
      - 'v2/**'

jobs:
  test-v1:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Lint Code
        uses: golangci/golangci-lint-action@v6

      - name: Check format
        run: test -z "`gofmt -l .`"

      - name: Run tests
        run: go test -v ./...

      - name: Build example
        run: cd example && ./linux64_build.sh
